name = "TightBindingToolBox"
uuid = "5b0e25c3-e409-4837-ae64-60157f6956a0"
authors = ["martinbrass <martinbrass@gmx.net> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"
WignerD = "87c4ff3e-34df-11e9-37a7-516cea4e0402"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
PlotsExt = "Plots"

[compat]
julia = "1.10"

[extras]
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Integrals","Test"]
